// bench/apps/astro/src/components/QuickView.tsx
// The quick view: a native <dialog>. For /?view=<id> the server renders it
// open, which works without JavaScript. Once hydrated, it opens as a modal
// whenever the catalog puts a product in the quick view store.
import { useStore } from '@nanostores/preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import { categoryName, formatPrice } from '../../../../scenario/markup.js';
import { $quickView, type ProductDetail } from '../stores/quick-view';
import AddToCart from './AddToCart';

export default function QuickView({ product: rendered }: { product: ProductDetail | null }) {
    const chosen = useStore($quickView);
    const dialog = useRef<HTMLDialogElement>(null);
    const product = chosen ?? rendered;

    // Open the dialog in the same frame that renders the product.
    useLayoutEffect(() => {
        const element = dialog.current;
        if (!chosen || !element || element.matches(':modal')) return;
        if (element.open) element.close(); // rendered open by the server, not as a modal
        element.showModal();
    }, [chosen]);

    return (
        // `open` only reflects the server render; after that the dialog's own methods open and close it.
        <dialog id="quick-view" aria-labelledby="quick-view-title" open={rendered !== null} ref={dialog}>
            {product ? (
                <div class="quick-view">
                    <img src={`/images/${product.id}.webp`} alt="" width={480} height={360} />
                    <div class="quick-view__body">
                        <h2 id="quick-view-title">{product.name}</h2>
                        <p class="meta">
                            <span>{categoryName(product.category)}</span> <span class="price">{formatPrice(product.price)}</span>
                        </p>
                        <p>{product.description}</p>
                        <div class="actions">
                            <AddToCart id={product.id} />
                            <form method="dialog">
                                <button>Close</button>
                            </form>
                        </div>
                    </div>
                </div>
            ) : null}
        </dialog>
    );
}

// bench/apps/qwik/src/components/quick-view/quick-view.tsx
import { component$, useSignal, useVisibleTask$, type Signal } from "@builder.io/qwik";
import { Form } from "@builder.io/qwik-city";
import { categoryName, formatPrice } from "../../../../../scenario/markup.js";
import type { Detail, useAddToCart } from "~/routes/index";

type AddToCart = ReturnType<typeof useAddToCart>;

interface Props {
  product: Signal<Detail | null>;
  /** Rendered open by the server, for ?view= without JavaScript. It never changes. */
  open: boolean;
  addToCart: AddToCart;
}

/**
 * The quick view is a native <dialog>. A card sets `product`; the content
 * renders, and then it opens the dialog as a modal. The dialog's `open`
 * attribute is left to the browser after the server rendered it.
 */
export const QuickView = component$<Props>((props) => {
  const dialog = useSignal<HTMLDialogElement>();
  return (
    <dialog id="quick-view" aria-labelledby="quick-view-title" open={props.open} ref={dialog}>
      {props.product.value && (
        <QuickViewContent product={props.product} dialog={dialog} addToCart={props.addToCart} />
      )}
    </dialog>
  );
});

interface ContentProps {
  product: Signal<Detail | null>;
  dialog: Signal<HTMLDialogElement | undefined>;
  addToCart: AddToCart;
}

const QuickViewContent = component$<ContentProps>(({ product, dialog, addToCart }) => {
  // showModal() has to wait until the product is in the DOM, and useVisibleTask$
  // is the task that runs after rendering. This component only exists once a
  // product has been chosen, so on the page as first served nothing runs early.
  useVisibleTask$(({ track }) => {
    track(product);
    if (dialog.value && !dialog.value.open) dialog.value.showModal();
  });
  const item = product.value;
  if (!item) return null;
  return (
    <div class="quick-view">
      <img src={`/images/${item.id}.webp`} alt="" width={480} height={360} />
      <div class="quick-view__body">
        <h2 id="quick-view-title">{item.name}</h2>
        <p class="meta">
          <span>{categoryName(item.category)}</span> <span class="price">{formatPrice(item.price)}</span>
        </p>
        <p>{item.description}</p>
        <div class="actions">
          <Form action={addToCart}>
            <input type="hidden" name="id" value={item.id} />
            <button>Add to cart</button>
          </Form>
          <form method="dialog">
            <button>Close</button>
          </form>
        </div>
      </div>
    </div>
  );
});
