// bench/apps/astro/src/components/AddToCart.tsx
// The add-to-cart form, in each card and in the quick view. Without
// JavaScript it posts to the page through the addToCart action; once its
// island has hydrated it calls the action from the browser instead.
import { actions } from 'astro:actions';
import type { TargetedSubmitEvent } from 'preact';
import { useState } from 'preact/hooks';
import { addToCart } from '../stores/cart';

export default function AddToCart({ id }: { id: string }) {
    const [busy, setBusy] = useState(false);

    async function submit(event: TargetedSubmitEvent<HTMLFormElement>) {
        event.preventDefault();
        setBusy(true);
        try {
            await addToCart(event.currentTarget);
        } finally {
            setBusy(false);
        }
    }

    return (
        <form method="post" action={actions.addToCart.queryString} onSubmit={submit} aria-busy={busy || undefined}>
            <input type="hidden" name="id" value={id} />
            <button>Add to cart</button>
        </form>
    );
}

// bench/apps/angular/src/app/add-to-cart.ts
import { Directive, inject, input } from '@angular/core';
import { Cart } from './cart';
import { handledByBrowser } from './replay';

/**
 * Enhances an "Add to cart" form. The form posts to /cart by itself, which
 * the server handles without JavaScript; once the page has hydrated, this
 * adds the product through the cart instead and the page stays as it is.
 */
@Directive({
  selector: 'form[appAddToCart]',
  host: { '(submit)': 'submit($event)' },
})
export class AddToCart {
  /** The product's id. */
  readonly product = input.required<string>({ alias: 'appAddToCart' });

  private readonly cart = inject(Cart);

  protected submit(event: SubmitEvent): void {
    if (handledByBrowser(event)) return;
    event.preventDefault();
    this.cart.add(this.product());
  }
}
