// bench/apps/nuxt/app/app.vue
<!--
  The shop's frame, shared by every page: the header with the cart, and the
  footer. The server reads the cart from the `cart` cookie (server/routes/
  cart.get.ts), so the header is rendered with it; adding to the cart replaces
  it with the cart the server answers with (see AddToCart.vue).
-->
<script setup lang="ts">
import { formatPrice } from '#scenario/markup.js'

const { data: cart } = await useFetch('/cart', { key: 'cart', default: () => ({ count: 0, total: 0 }) })
</script>

<template>
  <NuxtRouteAnnouncer />
  <header class="top">
    <NuxtLink class="brand" to="/">Wirestore</NuxtLink>
    <p class="cart">Cart <span id="cart-count">{{ cart.count }}</span> · <span id="cart-total">{{ formatPrice(cart.total) }}</span></p>
  </header>
  <NuxtPage />
  <footer class="bottom"><p>Wirestore is a benchmark scenario. Nothing here is for sale.</p></footer>
</template>

// bench/apps/solidstart/src/app.tsx
import { MetaProvider, Title } from "@solidjs/meta";
import { Router } from "@solidjs/router";
import { FileRoutes } from "@solidjs/start/router";
import { Suspense } from "solid-js";
import CartSummary from "~/components/CartSummary";

// The starter's app root: the router, the file routes, a metadata provider
// and a Suspense boundary around the page, with the shop's header and footer
// around every page. The cart in the header loads like route data, so it has
// a boundary of its own.
export default function App() {
  return (
    <Router
      root={props => (
        <MetaProvider>
          <Title>Wirestore</Title>
          <header class="top">
            <a class="brand" href="/">Wirestore</a>
            <Suspense>
              <CartSummary />
            </Suspense>
          </header>
          <Suspense>{props.children}</Suspense>
          <footer class="bottom"><p>Wirestore is a benchmark scenario. Nothing here is for sale.</p></footer>
        </MetaProvider>
      )}
    >
      <FileRoutes />
    </Router>
  );
}
