// bench/apps/sveltekit/src/lib/QuickView.svelte
<!--
	The quick view: a native <dialog>, open on `product` and empty otherwise.
	Opened in the browser (shallow routing), it is a modal. When /?view=<id> is
	loaded in full, it is open the way the server renders it, which is how the
	page shows it without JavaScript.
-->
<script>
	import { refreshAll } from '$app/navigation';
	import { categoryName, formatPrice } from '$scenario/markup.js';
	import AddToCart from './AddToCart.svelte';

	/**
	 * @type {{
	 *   product: { id: string, name: string, category: string, price: number, description: string } | null,
	 *   modal: boolean,
	 *   onclose: () => void
	 * }}
	 */
	let { product, modal, onclose } = $props();

	/**
	 * A modal makes the page behind it inert, moves focus into the dialog and
	 * closes on Escape.
	 * @param {HTMLDialogElement} dialog
	 */
	const showModal = (dialog) => dialog.showModal();

	/**
	 * After a success, use:enhance re-runs the load functions with invalidateAll,
	 * which also resets page.state and so would close a quick view opened with
	 * pushState. refreshAll re-runs them and keeps the page state.
	 * @type {import('@sveltejs/kit').SubmitFunction}
	 */
	const keepOpen = () => async ({ update }) => {
		await update({ invalidateAll: false });
		await refreshAll();
	};
</script>

{#snippet details(item)}
	<div class="quick-view">
		<img src="/images/{item.id}.webp" alt="" width="480" height="360" />
		<div class="quick-view__body">
			<h2 id="quick-view-title">{item.name}</h2>
			<p class="meta"><span>{categoryName(item.category)}</span> <span class="price">{formatPrice(item.price)}</span></p>
			<p>{item.description}</p>
			<div class="actions">
				<AddToCart id={item.id} submit={keepOpen} /><form method="dialog"><button>Close</button></form>
			</div>
		</div>
	</div>
{/snippet}

<!-- Each branch has fixed attributes, so the dialog's open state is left to the browser. -->
{#if product && modal}
	<dialog id="quick-view" aria-labelledby="quick-view-title" {@attach showModal} {onclose}>{@render details(product)}</dialog>
{:else if product}
	<dialog id="quick-view" aria-labelledby="quick-view-title" open {onclose}>{@render details(product)}</dialog>
{:else}
	<dialog id="quick-view" aria-labelledby="quick-view-title"></dialog>
{/if}

// bench/apps/solidstart/src/components/QuickView.tsx
import { Show, createEffect, on } from "solid-js";
import { categoryName, formatPrice } from "#scenario/markup.js";
import AddToCart from "./AddToCart";

type Product = { id: string; name: string; category: string; price: number; description: string };

/**
 * The quick view: a native <dialog id="quick-view">, open on a product and
 * empty otherwise. On a page loaded with ?view=<id>, the server renders it
 * open, which is how it shows without JavaScript, and it stays that way (not
 * modal) until it closes. Opened in the page, it is a modal: showModal()
 * makes the page behind it inert, moves the focus into it and lets Escape
 * close it. Its Close button is a <form method="dialog">, which closes it with
 * or without JavaScript.
 */
export default function QuickView(props: {
  product: Product | null | undefined;
  /** Called once the dialog has closed; `modal` says whether the page had opened it. */
  onClose: (modal: boolean) => void;
}) {
  let dialog!: HTMLDialogElement;
  const renderedOpen = Boolean(props.product);
  let modal = false;

  // Once the product's details are on the page, show them in a modal; when the
  // product goes away (Back), close it.
  createEffect(
    on(
      () => props.product,
      product => {
        if (product && !dialog.open) {
          dialog.showModal();
          modal = true;
        } else if (!product && dialog.open) dialog.close();
      },
      { defer: true },
    ),
  );

  function closed() {
    const wasModal = modal;
    modal = false;
    props.onClose(wasModal);
  }

  return (
    <dialog id="quick-view" aria-labelledby="quick-view-title" ref={dialog} open={renderedOpen} onClose={closed}>
      <Show when={props.product}>
        {product => (
          <div class="quick-view">
            <img src={`/images/${product().id}.webp`} alt="" width="480" height="360" />
            <div class="quick-view__body">
              <h2 id="quick-view-title">{product().name}</h2>
              <p class="meta"><span>{categoryName(product().category)}</span> <span class="price">{formatPrice(product().price)}</span></p>
              <p>{product().description}</p>
              <div class="actions">
                <AddToCart id={product().id} /><form method="dialog"><button>Close</button></form>
              </div>
            </div>
          </div>
        )}
      </Show>
    </dialog>
  );
}
