// bench/apps/solidstart/src/components/AddToCart.tsx
import { addToCart } from "~/lib/api";

/**
 * Adds one of a product to the cart. The form's action is the server
 * function's address, so without JavaScript the browser posts it there and is
 * sent back to the page; with it, the router sends it with fetch.
 */
export default function AddToCart(props: { id: string }) {
  return (
    <form action={addToCart} method="post">
      <input type="hidden" name="id" value={props.id} /><button>Add to cart</button>
    </form>
  );
}

// bench/apps/nuxt/app/components/AddToCart.vue
<!--
  Adds one of a product to the cart. Without JavaScript the browser posts the
  form to server/routes/cart.post.ts, which sets the cookie and redirects back
  to the page. With it, the same request goes out with $fetch, and the cart the
  server answers with replaces the header's (the `cart` data of app.vue).
-->
<script setup lang="ts">
const props = defineProps<{ id: string }>()

const { data: cart } = useNuxtData('cart')

async function add() {
  cart.value = await $fetch('/cart', { method: 'POST', body: { id: props.id } })
}
</script>

<template>
  <form method="post" action="/cart" @submit.prevent="add">
    <input type="hidden" name="id" :value="id"><button>Add to cart</button>
  </form>
</template>
